### ISSUE TITLE
Sortablejs and Input Range 

### ISSUE THREAD

**Issue by Alakeel** [myfrom/polymer-sortablejs#2]
I have an input range inside a sortable list. My issue is when I move the slider the whole element start dragging on the list while I change the range value. How can I prevent that to happen ? I tried to use Filter but it caused to not allow me to move the slider using mouse at all.

```
    <sortable-js filter=".ignore">
      <div>
          <p>Input (1)</p>
          <input type="range" min="1" max="100" value="50">
      </div>
       
      <div class="ignore">
          <p>Input (2) Filtered</p>
          <input type="range" min="1" max="100" value="50">
      </div>
    </sortable-js>
```

**Comment by myfrom** [comment]
There are a few solutions to that:

You can either **use handles**, [example](http://sortablejs.github.io/Sortable/#handle)

Or porbably better - add `class="ignore"` to **input element**, not the div and also set `preventOnFilter` to false on the sortable-js element. Sadly, you cannot set it in HTML, you have to set it JavaScript, so something like this:

```html
<sortable-js filter=".ignore">
  <div>
    <p>Input (1)</p>
    <input type="range" min="1" max="100" value="50"  class="ignore">
  </div>
     
  <div>
    <p>Input (2)</p>
    <input type="range" min="1" max="100" value="50" class="ignore">
  </div>
</sortable-js>
```
and in script:
```javascript
const sortable = document.querySelector('sortable-js'); // Or this.shadowRoot.querySelector('sortable-js') inside a Polymer 2 element
sortable.preventOnFilter = false;
```

**Comment by Alakeel** [comment]
Thanks @myfrom the second solution solved my issue.
